name: publish

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm i
      - run: npm i -g ardrive-cli
      - run: npm run deploy
        env:
          SEED: ${{ secrets.SEED }}
          WALLET64: ${{ secrets.WALLET64 }}
          GITAR_FOLDER_EID: ${{ secrets.GITAR_FOLDER_EID }}
